spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adls
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

azure:
  adls:
    client-id: your-client-id
    client-secret: your-client-secret
    tenant-id: your-tenant-id
    account-name: your-storage-account
    proxy:
      enabled: true
      host: proxy.example.com
      port: 3128

logging:
  file:
    name: logs/adls-scan.log
  level:
    root: INFO
    com.example: DEBUG  # Replace with your package name
